### PR TITLE
Switched namespace to Yiisoft

### PR DESCRIPTION
**Pull request by schmasterz**
| Q             | A
| ------------- | ---
| Breaks BC?    | yes

### CODE REVIEW

**Comment by samdark** [comment]
Should be `Yiisoft/Yii/Rest`.

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by machour** [comment]
@schmasterz can you take a look at the travis build and see what broke?

**Comment by samdark** [comment]
@machour wasn't it broken before?

**Comment by schmasterz** [comment]
I will try to fix it later this week

**Comment by machour** [comment]
it wasn't: https://travis-ci.org/yiisoft/yii-rest/builds

**Comment by machour** [comment]
@schmasterz it was a separate DI issue and it's now fixed.
Thank you so much for taking care of the namespace migration!

**Comment by larryli** [comment]
> Should be `Yiisoft/Yii/Rest`.

Will all Yii 3.0 packages switch to the FQN?

**Comment by samdark** [comment]
Yes.

**Pull request merged**
